name: 'pipeline_project_2'
version: '1.0.0'

profile: 'pipeline_project_2'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  pipeline_project_2:
    staging:
      +materialized: view
      +docs:
        node_color: "#cd7f32"
    intermediate:
      +materialized: view
      +docs:
        node_color: "#c0c0c0"
    marts:
      +materialized: table
      +docs:
        node_color: "#e6b530"
